// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfiwI_5sS0fnpOddI77OY6tI90icUtmk4',
    appId: '1:660206687276:web:1c58895b472d56fc81ad89',
    messagingSenderId: '660206687276',
    projectId: 'docstep-f9cfe',
    authDomain: 'docstep-f9cfe.firebaseapp.com',
    storageBucket: 'docstep-f9cfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AtlwbHYks7LoQj9h8XAydh1ufawIEpg',
    appId: '1:660206687276:android:021a6ce974d6cd3d81ad89',
    messagingSenderId: '660206687276',
    projectId: 'docstep-f9cfe',
    storageBucket: 'docstep-f9cfe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfqdQwMSZ-JSc45J6mtwrhf1WSfvbb1U',
    appId: '1:660206687276:ios:5965b9592a4793fa81ad89',
    messagingSenderId: '660206687276',
    projectId: 'docstep-f9cfe',
    storageBucket: 'docstep-f9cfe.firebasestorage.app',
    iosBundleId: 'pk.docstep.docstepMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfqdQwMSZ-JSc45J6mtwrhf1WSfvbb1U',
    appId: '1:660206687276:ios:5965b9592a4793fa81ad89',
    messagingSenderId: '660206687276',
    projectId: 'docstep-f9cfe',
    storageBucket: 'docstep-f9cfe.firebasestorage.app',
    iosBundleId: 'pk.docstep.docstepMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfiwI_5sS0fnpOddI77OY6tI90icUtmk4',
    appId: '1:660206687276:web:a7147ecb02bdbc1e81ad89',
    messagingSenderId: '660206687276',
    projectId: 'docstep-f9cfe',
    authDomain: 'docstep-f9cfe.firebaseapp.com',
    storageBucket: 'docstep-f9cfe.firebasestorage.app',
  );
}
